# Application Properties

# Server Configuration
server.port=4000

# LinkedIn OAuth Credentials
linkedin.client-id=8689oak1ll7q1n
linkedin.client-secret=REMOVED==

# Logging
logging.level.com.dobbie=DEBUG
